name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil codingan dari repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Login ke Docker Hub (Ini langkah yang tadi error)
    # Pastikan kamu sudah memasukkan DOCKER_USERNAME dan DOCKER_PASSWORD di Settings GitHub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Build (Membuat) dan Push (Upload) image ke Docker Hub
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        # Ganti 'awanbiru000/uas-devops' dengan nama image yang kamu mau
        # Format: username-dockerhub/nama-project:tag
        tags: awanbiru000/uas-devops:latest
